name: Basic-CI-TEst

# Specify the branch to work on
on:
  push:
    # Note: this will not work on initial commit or push of branch
    branches: [create-pipeline-from-scratch]
  # Examples of what on can do
  # pull_request:

  # schedule:
  #   - cron: '0 2 * * *'

  # paths:
  #   - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
