name: Basic-CI-Test

# Make sure the GITHUB_TOKEN has write permissions to contents
permissions:
  contents: write

# Specify the branch to work on
on:
  push:
    # Note: this will not work on initial commit or push of branch
    branches: [deploy-dev-merge-depoly-prod]
jobs:
  runTests:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install npm packages
        id: npm_install
        run: npm i

      - name: Run Tests
        run: npm run test

  bumpUpTheVersion:
    needs: runTests
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4
      - name: Configure Git User
        run: |
          # Configure Git user
          git config user.name "Julian Pickard"
          git config user.email "jpickard@and.digital"

          # Bump version (patch, minor, or major)
      - name: Bump Version
        run: |
          NEW_VERSION=$(npm version patch -m "Bump version to %s")
          echo "New version is: $NEW_VERSION"

      - name: Push Version Bump
        run: git push

  showDiff:
    needs: bumpUpTheVersion
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Fetch main branch
        run: git fetch origin main:main #This tells git to fetch main and update or create main in it's local storage

      - name: Show diff with main and my branch
        run: git diff main --stat

  buildDockerImage:
    needs: bumpUpTheVersion
    runs-on: ubuntu-latest
    environment: development

    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        # This is not the most secure way!
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t jpickard393/dockercicd -f Dockerfile .

      - name: Push Docker image
        run: docker push jpickard393/dockercicd
  deploy-to-development:
    needs: buildDockerImage
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: dockercicd-development
          images: ${{ secrets.DOCKER_IMAGE_NAME }}:latest

  merge-to-main:
    needs: deploy-to-development
    runs-on: ubuntu-latest
    steps:
      - name: checkout-main
        uses: actions/checkout@v4
      - name: Merge-deploy-dev-merge--deploy-prod into main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Get latest 'main'
          git checkout main
          git pull origin main

          git merge ${{ github.ref_name }} -m "Merge '${{ github.ref_name }}' with 'main after successful deploy to development'"
          git push origin main
