name: Basic-CI-TEst

# Specify the branch to work on
on:
  push:
    # Note: this will not work on initial commit or push of branch
    branches: [create-pipeline-from-scratch]
  # Examples of what on can do
  # pull_request:

  # schedule:
  #   - cron: '0 2 * * *'

  # paths:
  #   - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: npm i
      - name: Run_Tests
        run: npm run test
      - name: Echo success
        if: steps.Run_Tests.outcome == 'success'
        run: echo 'Success!'
      - name: Echo failure
        if: steps.Run_Tests.outcome != 'success'
        run: echo 'The Tests Have Failed'
