name: Basic-CI-Test

# Specify the branch to work on
on:
  push:
    # Note: this will not work on initial commit or push of branch
    branches: [version-and-diff]
jobs:
  runTests:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v3
      # We have to checkout the repo first or it does not work
      - name: Set up Git
        run: |
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: checkout
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git fetch origin
          git checkout version-and-diff

      - name: Install npm packages
        id: npm_install
        working-directory: ./repo
        run: npm i
      - name: Run Tests
        working-directory: ./repo
        run: npm run test

  buildDockerImage:
    needs: runTests
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: checkout
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git fetch origin
          git checkout version-and-diff

      - name: Log in to Docker Hub
        # This is not the most secure way!
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: ./repo
        run: docker build -t jpickard393/dockercicd -f Dockerfile .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}
  deploy:
    needs: buildDockerImage
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.DOCKER_IMAGE_NAME }}:latest
