name: Basic-CI-TEst

# Specify the branch to work on
on:
  push:
    # Note: this will not work on initial commit or push of branch
    branches: [create-pipeline-from-scratch]
  # Examples of what on can do
  # pull_request:

  # schedule:
  #   - cron: '0 2 * * *'

  # paths:
  #   - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: npm i
      - name: Run tests
        run: npm run test
