name: Basic-CI-TEst

# Specify the branch to work on
on:
  push:
    # Note: this will not work on initial commit or push of branch
    branches: [create-pipeline-from-scratch]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        run: npm i
      - name: Run_Tests
        run: npm run test
      - name: Echo success
        # if always makes sure that the next step always runs even if the one above fails
        if: always()
        run: |
          if [ "${{ steps.run_tests.outcome }}" == "success" ]; then
            echo "Success!"
          else
            echo "Tests fail"
          fi
