name: Basic-CI-Test
# Purpose
#
# On push to the branch
# Checkout
# Run tests
# If tests pass then build and deploy docker container

# Specify the branch to work on
on:
  push:
    # Note: this will not work on initial commit or push of branch
    branches: [create-pipeline-from-scratch]
jobs:
  runTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install npm packages
        id: npm_install
        run: npm i
      - name: Run Tests
        id: run_tests
        run: npm run test

  loginToDocker:
    runs-on: ubuntu-latest

    needs: runTests
    steps:
      - name: Log in to Docker Hub
        id: docker_login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

  buildDockerImage:
    needs: loginToDocker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t my-image-name -f path/to/Dockerfile .

  deploy:
    needs: buildDockerImage
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set --name ${{ secrets.AZURE_WEBAPP_NAME }} 
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} 
          --docker-custom-image-name ${{ secrets.DOCKER_USERNAME }}/dockercicd:latest
          az webapp restart --name dockercicdweb
          --resource-group cntainer-resgroup
