name: Deploy to Azure Web App

on:
  # workflow_run:
  #   workflows: ["Build Docker Image"]
  #   types:
  #     - completed
  push:
    branches:
      - feature/build-and-deploy-docker-image

jobs:
  build:
    runs-on: ubuntu-latest
    # check if previous job completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_IMAGE_NAME }}:latest

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy image to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.DOCKER_IMAGE_NAME }}:latest
