name: manual-checkout

on:
  workflow_call:

jobs:
  checkout_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: checkout
        run: |
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git fetch origin
          git checkout create-pipeline-from-scratch
